[programs.localnet]
nft_without_metaplex_and_candymachine = "AepCk26p7Q7zjmsnd79QLkbEJxXVQzgNfMAxfrKPwp4B"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/michael/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
